=== joanamaimo/Creaci-i-validaci-d-un-document-XML/recaudacion_peliculas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recaudacion_peliculas (pelicula*)>
<!ELEMENT pelicula (titulo, distribuidora, any_estreno, director, recaudaciones)>
<!ATTLIST pelicula id CDATA #REQUIRED>
<!ATTLIST pelicula any (2009 | 2012 | 2015 | 2018) #IMPLIED>
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT distribuidora (#PCDATA) >
<!ELEMENT any_estreno (#PCDATA) >
<!ELEMENT director (#PCDATA)>
<!ELEMENT recaudaciones (presupuesto, taquilla_EEUU, taquilla_fuera_EEUU, recaudacion_mundial)>
<!ELEMENT presupuesto (#PCDATA) >
<!ELEMENT taquilla_EEUU (#PCDATA) >
<!ELEMENT taquilla_fuera_EEUU (#PCDATA) >
<!ELEMENT recaudacion_mundial (#PCDATA) >

=== joanamaimo/Creaci-i-validaci-d-un-document-XML/recaudacion_peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recaudacion_peliculas SYSTEM "recaudacion_peliculas.dtd">
<recaudacion_peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recaudacion_peliculas.xsd">
  <pelicula id="1" año="2009">
    <titulo>Avatar</titulo>
	<distribuidora>20th Century Fox</distribuidora>
	<añoestreno>2009</añoestreno>
	<director>James Cameron</director>
	<recaudaciones>
		<presupuesto>237.000.000</presupuesto>
		<taquilla_EEUU>760.507.625</taquilla_EEUU>
		<taquilla_fuera_EEUU>2.027.457.462</taquilla_fuera_EEUU>
		<recaudacion_mundial>2.787.965.087</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="2">
    <titulo>Titanic</titulo>
	<distribuidora>20th Century Fox/Paramount Pictures</distribuidora>
	<añoestreno>1997</añoestreno>
	<director>James Cameron</director>
	<recaudaciones>
		<presupuesto>200.000.000</presupuesto>
		<taquilla_EEUU>659.363.944</taquilla_EEUU>
		<taquilla_fuera_EEUU>1.528.100.000</taquilla_fuera_EEUU>
		<recaudacion_mundial>2.187.463.944</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="3" año="2015">
    <titulo>Star Wars: Episodio VII - El despertar de la Fuerza</titulo>
	<distribuidora>Walt Disney Pictures</distribuidora>
	<añoestreno>2015</añoestreno>
	<director>J.J Abrams</director>
	<recaudaciones>
		<presupuesto>245.000.000</presupuesto>
		<taquilla_EEUU>936.662.225</taquilla_EEUU>
		<taquilla_fuera_EEUU>1.131.561.399</taquilla_fuera_EEUU>
		<recaudacion_mundial>2.068.223.624</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="4" año="2018">
    <titulo>Avengers: Infinity War</titulo>
	<distribuidora>Marvel Studios/Walt Disney Pictures</distribuidora>
	<añoestreno>2018</añoestreno>
	<director>Anthony y Joe Russo</director>
	<recaudaciones>
		<presupuesto>400.000.000</presupuesto>
		<taquilla_EEUU>678.815.482</taquilla_EEUU>
		<taquilla_fuera_EEUU>1.369.895,896</taquilla_fuera_EEUU>
		<recaudacion_mundial>2.048.711.378</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="5">
    <titulo>Jurassic World</titulo>
	<distribuidora>Universal Pictures</distribuidora>
	<añoestreno>2015</añoestreno>
	<director>Colin Trevorrow</director>
	<recaudaciones>
		<presupuesto>150.000.000</presupuesto>
		<taquilla_EEUU>652.270.625</taquilla_EEUU>
		<taquilla_fuera_EEUU>1.019.442.583</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.671.713.208</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="6">
    <titulo>The Avengers</titulo>
	<distribuidora>Marvel Studios/Walt Disney Pictures</distribuidora>
	<añoestreno>2012</añoestreno>
	<director>Joss Whedon</director>
	<recaudaciones>
		<presupuesto>220.000.000</presupuesto>
		<taquilla_EEUU>623.357.910</taquilla_EEUU>
		<taquilla_fuera_EEUU>895.455.078</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.518.812.988</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="7">
    <titulo>Furious 7</titulo>
	<distribuidora>Universal Studios</distribuidora>
	<añoestreno>2015</añoestreno>
	<director>James Wan</director>
	<recaudaciones>
		<presupuesto>190.000.000</presupuesto>
		<taquilla_EEUU>353.007.020</taquilla_EEUU>
		<taquilla_fuera_EEUU>1.163.038.891</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.516.045.911</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="8">
    <titulo>Avengers: Age of Ultron</titulo>
	<distribuidora>Marvel Studios/Walt Disney Pictures</distribuidora>
	<añoestreno>2015</añoestreno>
	<director>Joss Whedon</director>
	<recaudaciones>
		<presupuesto>250.000.000</presupuesto>
		<taquilla_EEUU>459.005.868</taquilla_EEUU>
		<taquilla_fuera_EEUU>946.497.926</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.405.983.798</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  <pelicula id="9">
    <titulo>Black Panther</titulo>
	<distribuidora>Marvel Studios/Walt Disney Pictures</distribuidora>
	<añoestreno>2018</añoestreno>
	<director>Ryan Coogler</director>
	<recaudaciones>
		<presupuesto>200.000.000</presupuesto>
		<taquilla_EEUU>700.059.566</taquilla_EEUU>
		<taquilla_fuera_EEUU>646.853.595</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.346.913.161</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
   <pelicula id="10">
    <titulo>Harry Potter y las Reliquias de la Muerte: parte 2</titulo>
	<distribuidora>Warner Bros</distribuidora>
	<añoestreno>2011</añoestreno>
	<director>David Yates</director>
	<recaudaciones>
		<presupuesto>250.000.000</presupuesto>
		<taquilla_EEUU>381.011.219</taquilla_EEUU>
		<taquilla_fuera_EEUU>960.500.000</taquilla_fuera_EEUU>
		<recaudacion_mundial>1.341.511.219</recaudacion_mundial>
	</recaudaciones>	
  </pelicula>
  </recaudacion_peliculas>
